thisislist = ["apple","banana","cherry"]
print(len(thisislist))
list1 = ["apple", "banana", "cherry"]
list2 = [1, 5, 7, 9, 3]
list3 = [True, False, False]
print(list1)
print(list2)
print(list3)
numbers = input("please enter two digits :\n")
first_number = int(numbers[0])
second_number = int(numbers[2])
print(first_number+second_number)
print(9/3)
print(2*3)
print(8-3*2)
birth_year = input("Enter your birth year : ")
age = 2023 - int(birth_year)
print(age)
first =(input("First: "))
second =(input("Second: "))
sum = float(first) +float(second)
print("sum : "+ str(sum))
print ("i am "+input("How old you ?\n")+ " years old")
print(input("where do you live ? \n") + " city")
user_pin=input("please enter your PIN number: \n")
print(len(user_pin))
print("Good Morning"[0])
print("Good Morning"[11])
print("Good Mornig"[10])
x=len(str(323423423))
print(x)
print(type(3))
print(type("3"))
name = input("what is your name ? \n")
print("Hello "+ name)
print(len(name))
print("Hello "+input ("what is your name ? \n"))
text = "Abdelkhalek Allan"
print(len(text))
name_len = len("name user")
print(name_len)
user_name = "Abdelkhalek Allan" #False
print("Hello " + user_name)
print("Done")